name: Meteo
description: "Météo"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  shared_preferences: ^2.2.2
  http:
  html:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

fonts:
  - family: Raleway
    fonts:
      - asset: lib/fonts/raleway.ttf

flutter:
  uses-material-design: true #include Material Icons font
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/cloud.png"
  min_sdk_android: 16
